name: "Metric existence check"
description: "Validate metric existence using python script quering against prometheus endpoint"
branding:
  color: blue
  icon: check-circle

inputs:
  endpoint:
    description: "Prometheus endpoint URL"
    required: true
  metric:
    description: "Prometheus metric to check"
    required: true
  label:
    description: "Label associated with the metric"
    required: true
  values:
    description: "Comma seperated list of values to check against, provide either this of netbox_* variables"
    required: false
  netbox_endpoint:
    description: "Netbox endpoint URL"
    required: false
  netbox_token:
    description: "Netbox API token"
    required: false

outputs:
  invalid_values:
    description: "Values that were not present in the metric check"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    METRICSURE_ENDPOINT: ${{ inputs.endpoint }}
    METRICSURE_METRIC: ${{ inputs.metric }}
    METRICSURE_LABEL: ${{ inputs.label }}
    METRICSURE_VALUES: ${{ inputs.values }}
    METRICSURE_NETBOX_ENDPOINT: ${{ inputs.netbox_endpoint }}
    METRICSURE_NETBOX_TOKEN: ${{ inputs.netbox_token }}
