name: Test metricsure
on: [push]
jobs:
  metricsure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run metricsure
        id: metricsure
        uses: ./
        with:
          endpoint: 'https://prometheus.demo.do.prometheus.io'
          metric: 'prometheus_remote_storage_exemplars_in_total'
          label: 'instance'
          values: 'demo.do.prometheus.io:9100,demo.do.prometheus.io:9090'

      - name: send message
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "Metrics are not available for: \n```${{steps.metricsure.outputs.invalid_values}}```"
